const lessons=[
["Study Smarter","Learn one small topic at a time. Set a clear target, remove distractions, practise actively, and review later.","Choose one small target instead of trying to learn everything at once."],
["English Speaking","Speak slowly and use short sentences. Listen, repeat, record yourself, and try again. Mistakes are part of learning.","Practise speaking for 10 minutes every day."],
["Financial Management","Financial management is the planning, obtaining, using and controlling of money in a business. Main decisions include investment, financing and dividend decisions.","Remember: investment + financing + dividend."],
["Interview Preparation","An interview self-introduction should briefly cover your name, education, skills, interests and career goal.","Practise your introduction aloud before an interview."]
];
const words=[
["Accurate","AK-yuh-rət","adjective","Correct and free from mistakes","Please provide accurate information.","B1"],
["Adapt","uh-DAPT","verb","To change to suit a new situation","Students must adapt to new learning methods.","B1"],
["Benefit","BEN-uh-fit","noun","An advantage","Reading daily has many benefits.","B1"],
["Confident","KON-fi-dənt","adjective","Sure about your ability","I feel confident about my interview.","B1"],
["Efficient","ih-FISH-ənt","adjective","Working well without wasting time","This is an efficient study method.","B2"],
["Evaluate","ih-VAL-yoo-ayt","verb","To judge or assess","We evaluate the investment before deciding.","B2"],
["Relevant","REL-uh-vənt","adjective","Connected with the topic","Give only relevant information.","B2"],
["Sustainable","suh-STAY-nuh-bəl","adjective","Able to continue for a long time","The company needs a sustainable strategy.","B2"],
["Resilient","ri-ZIL-yənt","adjective","Able to recover after difficulty","A resilient learner keeps trying.","B2"],
["Improve","im-PROOV","verb","To make better","I want to improve my communication.","A2"]
];
const quiz=[
["What is financial management?",["Planning and controlling business money","Only advertising","Only hiring staff","Only selling"],0,"It involves planning, obtaining, using and controlling business funds."],
["Which habit improves speaking?",["Never speaking","Regular speaking practice","Only reading grammar","Avoiding mistakes"],1,"Regular speaking practice builds fluency and confidence."],
["What does accurate mean?",["Correct and without mistakes","Very expensive","Very fast","Difficult"],0,"Accurate means correct and free from mistakes."],
["What does sustainable mean?",["Temporary","Able to continue for a long time","Incorrect","Unrelated"],1,"Sustainable means able to continue over a long period."],
["Which is a good study method?",["One small target every day","No revision","Study once a month","Never practise"],0,"Small, regular targets make learning consistent."]
];
const S={page:"home",lesson:0,word:0,q:0,score:0,answered:false,done:+localStorage.getItem("dl_done")||0,seen:+localStorage.getItem("dl_seen")||0,theme:localStorage.getItem("dl_theme")||"light",name:localStorage.getItem("dl_name")||"Student"};
const app=document.getElementById("app"),modal=document.getElementById("modal");
function save(){localStorage.setItem("dl_done",S.done);localStorage.setItem("dl_seen",S.seen);localStorage.setItem("dl_theme",S.theme);localStorage.setItem("dl_name",S.name)}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function speak(t){if(!("speechSynthesis"in window)){toast("Speech is not supported.");return}speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}
function head(a,b){return `<div class="head"><h2>${a}</h2><p class="muted">${b}</p></div>`}
function feature(i,t,d,p){return `<button class="card feature" data-page="${p}"><div class="ico">${i}</div><h3>${t}</h3><p class="muted">${d}</p></button>`}
function home(){let pct=Math.round(S.done/lessons.length*100);return `<section class="hero"><div><span class="eyebrow">YOUR DAILY STUDY SPACE</span><h1>Learn something useful every day.</h1><p>Build English, academic knowledge and confidence with short lessons, vocabulary, speaking practice, grammar and quizzes.</p><div class="row"><button class="btn primary" data-action="start">Start learning →</button><button class="btn secondary" data-page="ai">Ask AI Tutor</button></div></div><div class="hero-card"><p class="muted">Today's progress</p><div class="big">${pct}%</div><div class="progress"><i style="width:${pct}%"></i></div><p class="muted">${S.done}/${lessons.length} lessons completed</p></div></section><div class="stats"><div class="stat">🔥 Streak<strong>1 day</strong><span class="muted">Keep learning.</span></div><div class="stat">🧠 Words<strong>${S.seen}</strong><span class="muted">Vocabulary practice.</span></div><div class="stat">🏆 Quiz<strong>${S.score}/${quiz.length}</strong><span class="muted">This session.</span></div></div><section class="section"><h2>Learn today</h2><p class="muted">All sections are inside this one website—no missing pages.</p><div class="grid">${feature("📚","Lessons","Short lessons for English, finance and study skills.","lessons")}${feature("🧠","Vocabulary","Useful words with meaning, examples and audio.","vocabulary")}${feature("🗣️","Speaking","Practise useful English sentences aloud.","speaking")}${feature("✍️","Grammar","Fix common English mistakes.","grammar")}${feature("❓","Quiz","Answer questions and see explanations.","quiz")}${feature("🤖","AI Tutor","Ask study questions. Works without an API key.","ai")}</div></section>`}
function lessonsPage(){let l=lessons[S.lesson];return `${head("Daily Lessons","Short lessons you can complete one by one.")}<div class="lesson"><article class="card lesson-main"><span class="eyebrow">LESSON ${S.lesson+1}/${lessons.length}</span><h2>${l[0]}</h2><p>${l[1]}</p><div class="tip">💡 <strong>Key idea:</strong> ${l[2]}</div><div class="row"><button class="btn secondary" data-action="prevLesson">← Previous</button><button class="btn primary" data-action="complete">Mark complete ✓</button><button class="btn secondary" data-action="nextLesson">Next →</button></div></article><aside class="card"><h3>Lessons</h3>${lessons.map((x,i)=>`<button class="btn ${i===S.lesson?"primary":"secondary"}" style="width:100%;margin-top:8px;text-align:left" data-lesson="${i}">${i+1}. ${x[0]}</button>`).join("")}</aside></div>`}
function vocabularyPage(){let w=words[S.word];return `${head("Vocabulary","Learn useful words and hear pronunciation.")}<div class="card word"><span class="eyebrow">${w[5]} • ${w[2]}</span><h1>${w[0]}</h1><div class="phonetic">/${w[1]}/</div><p><strong>Meaning:</strong> ${w[3]}</p><div class="example"><strong>Example:</strong> ${w[4]}</div><div class="row" style="justify-content:center"><button class="btn secondary" data-action="wordSpeak">🔊 Listen</button><button class="btn primary" data-action="nextWord">Next word →</button></div></div><div class="section"><h3>Useful words</h3><div class="grid">${words.slice(0,6).map(w=>`<div class="card"><strong>${w[0]}</strong><p class="muted">${w[3]}</p></div>`).join("")}</div></div>`}
function speakingPage(){let a=["My name is Vinith.","I am studying MBA in Finance.","I want to improve my communication skills.","I practise English every day.","I am preparing for a corporate career."],i=+(localStorage.getItem("dl_speak")||0);return `${head("English Speaking Practice","Listen, repeat, and practise with confidence.")}<div class="card" style="max-width:800px;margin:auto;text-align:center"><span class="eyebrow">SENTENCE ${i+1}/${a.length}</span><h2 style="margin:18px 0">${a[i]}</h2><p class="muted">Say it aloud three times.</p><div class="row" style="justify-content:center"><button class="btn primary" data-action="sentenceSpeak">🔊 Listen</button><button class="btn secondary" data-action="nextSentence">Next sentence</button></div><div class="tip" style="text-align:left">🎯 Speak slowly. Clear English is more important than speaking very fast.</div></div>`}
function grammarPage(){return `${head("Grammar Practice","Choose the correct sentence.")}<div class="card"><h3>Which sentence is correct?</h3><div class="options"><button class="option" data-grammar="0">She go to college every day.</button><button class="option" data-grammar="1">She goes to college every day.</button></div><p id="grammarFeedback" class="muted">Choose an answer.</p></div><div class="card" style="margin-top:16px"><h3>Quick rule</h3><p>With <strong>he, she, it</strong> in the simple present, the verb usually takes <strong>-s</strong> or <strong>-es</strong>.</p></div>`}
function quizPage(){let q=quiz[S.q];return `${head("Daily Quiz","Choose an answer and get an instant explanation.")}<div class="card" style="max-width:800px;margin:auto"><span class="eyebrow">QUESTION ${S.q+1}/${quiz.length}</span><h2>${q[0]}</h2><div class="options">${q[1].map((x,i)=>`<button class="option" data-option="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join("")}</div><p id="quizFeedback" class="muted">Choose an answer.</p><button class="btn primary" data-action="nextQuiz">Next question →</button></div>`}
function aiPage(){return `${head("AI Tutor","Ask about English, MBA, finance, coding, science or study topics.")}<div class="chat"><div id="messages" class="messages"><div class="msg bot">Hello ${S.name}! 👋 I am your Daily Learning Tutor. Ask me a question and I will explain it simply.</div></div><div class="quick"><button data-query="What is financial management?">Financial management</button><button data-query="Explain working capital simply">Working capital</button><button data-query="Correct: She go to college">Grammar correction</button><button data-query="What does resilient mean?">Vocabulary</button></div><div class="chatbar"><input id="aiInput" placeholder="Ask anything you want to learn..."><button class="btn secondary" data-action="voice">🎙️</button><button class="btn primary" data-action="ask">Send</button></div><div class="row" style="margin-top:10px"><button class="btn secondary" data-action="clearChat">Clear chat</button><button class="btn secondary" data-action="readLast">🔊 Read last answer</button></div><div class="tip">This tutor works without an API key, so the website buttons do not depend on Gemini. A secure backend can be added later for unlimited AI answers.</div></div>`}
function progressPage(){let pct=Math.round(S.done/lessons.length*100);return `${head("My Progress","Your progress is saved in this browser.")}<div class="stats"><div class="stat">📚 Lessons<strong>${S.done}/${lessons.length}</strong></div><div class="stat">🧠 Words<strong>${S.seen}</strong></div><div class="stat">🏆 Quiz<strong>${S.score}/${quiz.length}</strong></div></div><div class="card" style="margin-top:18px"><h3>Lesson completion</h3><div class="progress" style="margin:14px 0"><i style="width:${pct}%"></i></div><p>${pct}% complete.</p><button class="btn danger" data-action="reset">Reset progress</button></div>`}
function localAI(q){let x=q.toLowerCase();if(x.includes("financial management")||x.includes("finance"))return"Financial management means planning, obtaining, using and controlling money in a business. The main decisions are: 1) investment—where to invest, 2) financing—how to raise money, and 3) dividend—how much profit to distribute. Example: a company compares projects before investing.";if(x.includes("working capital"))return"Working capital is the money available for day-to-day operations. Formula: Current Assets − Current Liabilities. Example: ₹5 lakh current assets − ₹3 lakh current liabilities = ₹2 lakh working capital.";if(x.includes("go to college")||x.includes("grammar")||x.includes("correct"))return"Correct sentence: “She goes to college every day.” Rule: with he, she or it in the simple present, the verb usually takes -s or -es.";if(x.includes("resilient"))return"Resilient means able to recover from difficulties and continue trying. Example: A resilient student learns from mistakes and keeps practising.";if(x.includes("confident"))return"Confident means feeling sure about your ability. Example: I feel confident before my interview.";if(x.includes("tally"))return"TallyPrime is accounting and business-management software used for transactions, ledgers, invoices, inventory and financial reports.";if(x.includes("english")||x.includes("speaking"))return"To improve English speaking: practise 10 minutes daily, learn 5 useful words, speak short sentences, listen and repeat, record yourself, and review one mistake at a time.";if(x.includes("mba"))return"MBA means Master of Business Administration. Common areas include finance, marketing, HR, operations and strategy. A good answer gives the definition, key points and an example.";if(x.includes("capital structure"))return"Capital structure is the mix of debt and equity used to finance a company's assets and operations. Example: bank loans plus shareholders' equity.";if(x.includes("hello")||x.includes("hi"))return"Hello! 👋 What would you like to learn today? Ask about English, MBA, finance, accounting, interviews, vocabulary, grammar or study skills.";return"I can help you learn. Try: “What is working capital?”, “Explain capital structure simply”, “Correct my English sentence”, “What is TallyPrime?”, or “Explain this MBA topic with an example.”"}
function addMsg(t,w){let m=document.getElementById("messages");if(!m)return;let d=document.createElement("div");d.className="msg "+w;d.textContent=t;m.appendChild(d);m.scrollTop=m.scrollHeight}
function askAI(){let i=document.getElementById("aiInput");if(!i)return;let q=i.value.trim();if(!q){toast("Type a question first.");return}addMsg(q,"user");i.value="";setTimeout(()=>addMsg(localAI(q),"bot"),200)}
function quizAnswer(i,b){if(S.answered)return;S.answered=true;let q=quiz[S.q];document.querySelectorAll("[data-option]").forEach((x,n)=>{if(n===q[2])x.classList.add("correct")});if(i===q[2]){S.score++;document.getElementById("quizFeedback").innerHTML='<span style="color:var(--green);font-weight:800">Correct ✓</span> '+q[3]}else{b.classList.add("wrong");document.getElementById("quizFeedback").textContent="Not quite. "+q[3]}save()}
function startVoice(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast("Voice input is not supported in this browser.");return}let r=new R();r.lang="en-IN";r.onresult=e=>{let i=document.getElementById("aiInput");if(i)i.value=e.results[0][0].transcript};r.onerror=()=>toast("Voice input could not start.");r.start()}
function profile(){modal.classList.remove("hidden");modal.innerHTML=`<div class="modal-box"><h2>Your Profile</h2><p class="muted">Name is stored only in this browser.</p><input class="field" id="nameInput" value="${S.name.replace(/"/g,"&quot;")}" placeholder="Your name"><button class="btn primary" style="width:100%" data-action="saveName">Save</button><button class="btn secondary" style="width:100%;margin-top:8px" data-action="closeModal">Close</button></div>`;modal.querySelector("[data-action=closeModal]").onclick=()=>modal.classList.add("hidden");modal.querySelector("[data-action=saveName]").onclick=()=>{let n=document.getElementById("nameInput").value.trim();if(n){S.name=n;save();modal.classList.add("hidden");toast("Profile saved.");render()}}}
function bind(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=e=>{e.preventDefault();S.page=b.dataset.page;document.getElementById("mobileNav").classList.remove("open");render()});document.querySelectorAll("[data-lesson]").forEach(b=>b.onclick=()=>{S.lesson=+b.dataset.lesson;render()});document.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>quizAnswer(+b.dataset.option,b));document.querySelectorAll("[data-grammar]").forEach(b=>b.onclick=()=>{document.getElementById("grammarFeedback").innerHTML=b.dataset.grammar==="1"?'<span style="color:var(--green);font-weight:800">Correct ✓</span> “She goes to college every day.”':'<span style="color:var(--red);font-weight:800">Not correct.</span> Use “goes” with she.'});document.querySelectorAll("[data-query]").forEach(b=>b.onclick=()=>{let i=document.getElementById("aiInput");i.value=b.dataset.query;askAI()});const A={start:()=>{S.page="lessons";render()},prevLesson:()=>{S.lesson=Math.max(0,S.lesson-1);render()},nextLesson:()=>{S.lesson=Math.min(lessons.length-1,S.lesson+1);render()},complete:()=>{S.done=Math.max(S.done,S.lesson+1);save();toast("Lesson completed ✓");render()},wordSpeak:()=>speak(words[S.word][0]),nextWord:()=>{S.word=(S.word+1)%words.length;S.seen++;save();render()},sentenceSpeak:()=>{let a=["My name is Vinith.","I am studying MBA in Finance.","I want to improve my communication skills.","I practise English every day.","I am preparing for a corporate career."];speak(a[+(localStorage.getItem("dl_speak")||0)])},nextSentence:()=>{let i=+(localStorage.getItem("dl_speak")||0);localStorage.setItem("dl_speak",(i+1)%5);render()},nextQuiz:()=>{S.q=(S.q+1)%quiz.length;S.answered=false;render()},ask:askAI,voice:startVoice,clearChat:()=>{document.getElementById("messages").innerHTML='<div class="msg bot">Chat cleared. Ask me a new question.</div>'},readLast:()=>{let a=[...document.querySelectorAll("#messages .bot")].pop();if(a)speak(a.textContent)},reset:()=>{S.done=0;S.seen=0;S.score=0;save();toast("Progress reset.");render()},profile};document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>A[b.dataset.action]?.());let i=document.getElementById("aiInput");if(i)i.onkeydown=e=>{if(e.key==="Enter")askAI()}}
function render(){let p={home,lessons:lessonsPage,vocabulary:vocabularyPage,speaking:speakingPage,grammar:grammarPage,quiz:quizPage,ai:aiPage,progress:progressPage};app.innerHTML=(p[S.page]||home)();document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===S.page));bind()}
document.getElementById("themeBtn").onclick=()=>{S.theme=S.theme==="dark"?"light":"dark";document.body.classList.toggle("dark",S.theme==="dark");save();document.getElementById("themeBtn").textContent=S.theme==="dark"?"☀️":"🌙"};
document.getElementById("menuBtn").onclick=()=>document.getElementById("mobileNav").classList.toggle("open");
document.body.classList.toggle("dark",S.theme==="dark");document.getElementById("themeBtn").textContent=S.theme==="dark"?"☀️":"🌙";render();